export const INDIAN_STATES_AND_UNION_TERRITORIES = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
] as const;

// Commonly used Indian cities, including state and union-territory capitals.
// The API accepts the selected names as the canonical location values.
export const INDIAN_CITIES = [
  "Agartala", "Agra", "Ahmedabad", "Aizawl", "Ajmer", "Alappuzha", "Aligarh", "Amaravati", "Ambala", "Amritsar",
  "Anand", "Asansol", "Aurangabad", "Bareilly", "Belagavi", "Bengaluru", "Berhampur", "Bharatpur", "Bhilai", "Bhopal",
  "Bhubaneswar", "Bikaner", "Bilaspur", "Bokaro", "Chandigarh", "Chennai", "Coimbatore", "Cuttack", "Dehradun", "Delhi",
  "Dhanbad", "Dharamshala", "Dibrugarh", "Dimapur", "Durgapur", "Ernakulam", "Faridabad", "Gandhinagar", "Gangtok", "Gaya",
  "Ghaziabad", "Gorakhpur", "Gurugram", "Guwahati", "Gwalior", "Hamirpur", "Haridwar", "Hisar", "Hosur", "Hubballi",
  "Hyderabad", "Imphal", "Indore", "Itanagar", "Jabalpur", "Jaipur", "Jalandhar", "Jammu", "Jamnagar", "Jamshedpur",
  "Jhansi", "Jodhpur", "Kakinada", "Kalyan-Dombivli", "Kanpur", "Karnal", "Kochi", "Kohima", "Kolkata", "Kollam",
  "Kota", "Kottayam", "Kozhikode", "Kurnool", "Latur", "Leh", "Lucknow", "Ludhiana", "Madurai", "Mangaluru",
  "Meerut", "Moradabad", "Mumbai", "Munger", "Mysuru", "Nagpur", "Nainital", "Nashik", "Navi Mumbai", " Nellore",
  "Noida", "Panaji", "Panipat", "Patiala", "Patna", "Pimpri-Chinchwad", "Pondicherry", "Port Blair", "Prayagraj", "Pune",
  "Raipur", "Rajahmundry", "Rajkot", "Ranchi", "Rishikesh", "Rohtak", "Rourkela", "Sagar", "Salem", "Sangli",
  "Shillong", "Shimla", "Shivamogga", "Siliguri", "Silchar", "Srinagar", "Surat", "Thane", "Thanjavur", "Thiruvananthapuram",
  "Thrissur", "Tiruchirappalli", "Tirunelveli", "Tirupati", "Udaipur", "Ujjain", "Vadodara", "Varanasi", "Vasai-Virar", "Vellore",
  "Vijayawada", "Visakhapatnam", "Warangal", "Wardha", "Yamunanagar",
].map((city) => city.trim()).sort((first, second) => first.localeCompare(second));
