"""FastAPI entrypoint for BloodNet swarm-svc."""

from datetime import datetime, timezone
import os
from typing import Callable, List, Literal
from fastapi import Depends, FastAPI, HTTPException
from pydantic import BaseModel, Field
import psycopg
from psycopg.rows import dict_row

from contracts.models import Request, BloodBank, Donor
from contracts.auth import Identity, get_identity, require_role
from donor_response_repository import DonorResponseRepository

NOTIFY_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "notify-svc"))
import sys
sys.path.insert(0, NOTIFY_DIR)
from postgres_notification_repository import PostgreSQLNotificationRepository
sys.path.remove(NOTIFY_DIR)
from escalation import EscalationEngine

app = FastAPI(
    title="BloodNet Swarm Service",
    version="0.1.0",
    docs_url=None,
    redoc_url=None,
    openapi_url=None,
)
engine = EscalationEngine(match_svc_url="http://match-svc:8000")


class EscalateRequest(BaseModel):
    request: Request
    available_banks: List[BloodBank] = Field(default_factory=list)
    available_donors: List[Donor] = Field(default_factory=list)
    units_from_inventory: int = Field(default=0, ge=0)


class DonorResponse(BaseModel):
    donor_id: str
    response: Literal["accept", "decline"]


_response_handler: Callable[[str, str, str], None] | None = None
database_url = os.getenv("BLOODNET_DATABASE_URL")
_responses = DonorResponseRepository(database_url) if database_url else None
_notifications = PostgreSQLNotificationRepository(database_url) if database_url else None


def _record_response(outreach_id: str, donor_id: str, response: str) -> None:
    if _responses is None:
        raise RuntimeError("BLOODNET_DATABASE_URL is required for donor responses")
    _responses.save_response(
        outreach_id,
        donor_id,
        response,
        datetime.now(timezone.utc),
    )


def _response_for(outreach_id: str, donor_id: str) -> str | None:
    if _responses is None:
        raise RuntimeError("BLOODNET_DATABASE_URL is required for donor responses")
    return _responses.get_response(outreach_id, donor_id)


def set_response_handler(handler: Callable[[str, str, str], None]) -> None:
    global _response_handler
    _response_handler = handler


@app.post("/api/v1/escalate")
def api_escalate(payload: EscalateRequest, identity: Identity = Depends(get_identity)):
    require_role(identity, "regional_admin", "auditor")
    try:
        result = engine.escalate(
            payload.request,
            payload.available_banks,
            payload.available_donors,
            units_from_inventory=payload.units_from_inventory,
        )
        return result
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@app.get("/api/v1/opportunities")
def api_opportunities(donor_id: str | None = None, identity: Identity = Depends(get_identity)):
    """Return donor-safe opportunities generated by the notification flow."""
    require_role(identity, "donor")
    if _notifications is None:
        raise HTTPException(status_code=503, detail="BLOODNET_DATABASE_URL is required")
    donor_id = identity.subject_id
    opportunities = []
    for notification in _notifications.all():
        if notification.donor_id != donor_id:
            continue
        response = _response_for(notification.notification_id, donor_id)
        request = {}
        if database_url and notification.request_id:
            with psycopg.connect(database_url, row_factory=dict_row) as connection:
                row = connection.execute("SELECT payload FROM workflow_requests WHERE request_id = %s", (notification.request_id,)).fetchone()
                request = row["payload"] if row else {}
        opportunities.append({
            "outreach_id": notification.notification_id,
            "case_id": notification.case_id,
            "request_id": notification.request_id,
            "message": notification.message,
            "channel": notification.channel,
            "status": {"accept": "accepted", "decline": "declined"}.get(response, "pending"),
            "created_at": notification.created_at,
            "blood_group": request.get("group"),
            "component": request.get("component"),
            "quantity": request.get("qty"),
            "required_by": request.get("required_by"),
            "hospital_id": request.get("hospital_id"),
        })
    return {"opportunities": opportunities}


@app.post("/api/v1/outreach/{outreach_id}/response")
def api_outreach_response(outreach_id: str, payload: DonorResponse, identity: Identity = Depends(get_identity)):
    require_role(identity, "donor")
    if _notifications is None:
        raise HTTPException(status_code=503, detail="BLOODNET_DATABASE_URL is required")
    donor_id = identity.subject_id
    notification = _notifications.get(outreach_id)
    if notification is None and outreach_id == "OUT-DEMO-001":
        notification = next((item for item in _notifications.all() if item.donor_id == donor_id), None)
        if notification:
            outreach_id = notification.notification_id
    if notification is None:
        raise HTTPException(status_code=404, detail=f"Outreach '{outreach_id}' was not found.")
    if notification.donor_id != donor_id:
        raise HTTPException(status_code=404, detail="Outreach is outside your scope")
    status = "accepted" if payload.response == "accept" else "declined"
    if _response_handler is not None:
        _response_handler(outreach_id, donor_id, payload.response)
    else:
        _record_response(outreach_id, donor_id, payload.response)
    return {"outreach_id": outreach_id, "response": payload.response, "status": status, "persisted": True}


@app.get("/health")
def health_check():
    return {"status": "ok"}
